name: latexmk
on:
  push:
jobs:
  latexmk:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4
      - name: build pdfs
        uses: docker://texlive/texlive:latest
        with:
          args: make all
      - name: upload pdfs
        uses: actions/upload-artifact@v4
        with:
          name: all-pdfs
          path: pdf/
